SOURCE is block 5 DESTINATION is block 2


2016-11-11 09:43:19.585 1455 WARNING os_brick.initiator.linuxfc [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] systool is not installed
2016-11-11 09:43:19.659 1455 WARNING os_brick.initiator.linuxfc [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] systool is not installed
2016-11-11 09:43:19.764 1455 INFO nova.compute.manager [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26] Swapping volume 61a92987-9b37-4322-8c12-e83063e8e938 for 6b5a833f-55ca-4ecc-8df8-5c0c2dadc6d7


2016-11-11 09:43:20.444 1455 INFO os_brick.initiator.connector [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] Multipath discovery for iSCSI not enabled.
2016-11-11 09:43:20.446 1455 INFO os_brick.initiator.connector [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] Trying to connect to iSCSI portal 10.18.75.62:3260

	Some times this line does not happen
2016-11-11 09:43:22.372 1455 WARNING os_brick.initiator.connector [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] ISCSI volume not yet found at: [u'/dev/disk/by-path/ip-10.18.75.62:3260-iscsi-iqn.2010-10.org.openstack:volume-6b5a833f-55ca-4ecc-8df8-5c0c2dadc6d7-lun-1']. Will rescan & retry.  Try number: 0.


2016-11-11 09:43:51.820 1455 INFO nova.compute.resource_tracker [req-161708aa-781e-4ff9-a52d-49d684129673 - - - - -] Auditing locally available compute resources for node compute3
2016-11-11 09:43:53.248 1455 INFO nova.compute.resource_tracker [req-161708aa-781e-4ff9-a52d-49d684129673 - - - - -] Total usable vcpus: 8, total allocated vcpus: 11
2016-11-11 09:43:53.249 1455 INFO nova.compute.resource_tracker [req-161708aa-781e-4ff9-a52d-49d684129673 - - - - -] Final resource view: name=compute3 phys_ram=16047MB used_ram=23040MB phys_disk=591GB used_disk=220GB total_vcpus=8 used_vcpus=11 pci_stats=[]
2016-11-11 09:43:53.256 1455 INFO nova.compute.resource_tracker [req-161708aa-781e-4ff9-a52d-49d684129673 - - - - -] Compute_service record updated for compute3:compute3
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26] Failed to swap volume 61a92987-9b37-4322-8c12-e83063e8e938 for 6b5a833f-55ca-4ecc-8df8-5c0c2dadc6d7
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26] Traceback (most recent call last):
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4924, in _swap_volume
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     resize_to)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1428, in swap_volume
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     self._swap_volume(guest, disk_dev, conf.source_path, resize_to)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1398, in _swap_volume
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     self._host.write_instance_config(xml)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/host.py", line 981, in write_instance_config
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     return self.get_connection().defineXML(xml)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 186, in doit
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     result = proxy_call(self._autowrap, f, *args, **kwargs)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 144, in proxy_call
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     rv = execute(f, *args, **kwargs)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 125, in execute
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     six.reraise(c, e, tb)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 83, in tworker
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     rv = meth(*args, **kwargs)
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 3650, in defineXML
2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26]     if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)




2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26] libvirtError: block copy still active: domain has active block job



2016-11-11 09:43:56.366 1455 ERROR nova.compute.manager [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26] 
2016-11-11 09:43:56.789 1455 INFO nova.compute.manager [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] [instance: 38b4d2ba-7421-4c00-9d0a-ad84137eee26] Successfully reverted task state from None on failure for instance.


2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher [req-3100f5e0-5f92-462c-8fa1-5c71af02586f 275716005ea14ce8a8e1c4a7c05c6ccc 666da5edb7dd4ac1a642a1fdd0f0f8f0 - - -] Exception during message handling: block copy still active: domain has active block job
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 138, in _dispatch_and_reply
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     incoming.message))
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 185, in _dispatch
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 127, in _do_dispatch
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/exception.py", line 110, in wrapped
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     payload)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self.force_reraise()
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     six.reraise(self.type_, self.value, self.tb)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/exception.py", line 89, in wrapped
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     return f(self, context, *args, **kw)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 359, in decorated_function
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     LOG.warning(msg, e, instance=instance)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self.force_reraise()
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     six.reraise(self.type_, self.value, self.tb)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 328, in decorated_function
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     return function(self, context, *args, **kwargs)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 387, in decorated_function
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     kwargs['instance'], e, sys.exc_info())
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self.force_reraise()
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     six.reraise(self.type_, self.value, self.tb)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 375, in decorated_function
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     return function(self, context, *args, **kwargs)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4991, in swap_volume
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     resize_to)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4943, in _swap_volume
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self.volume_api.unreserve_volume(context, new_volume_id)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self.force_reraise()
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     six.reraise(self.type_, self.value, self.tb)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 4924, in _swap_volume
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     resize_to)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1428, in swap_volume
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self._swap_volume(guest, disk_dev, conf.source_path, resize_to)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1398, in _swap_volume
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     self._host.write_instance_config(xml)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/host.py", line 981, in write_instance_config
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     return self.get_connection().defineXML(xml)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 186, in doit
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     result = proxy_call(self._autowrap, f, *args, **kwargs)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 144, in proxy_call
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     rv = execute(f, *args, **kwargs)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 125, in execute
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     six.reraise(c, e, tb)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/eventlet/tpool.py", line 83, in tworker
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     rv = meth(*args, **kwargs)
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 3650, in defineXML
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher     if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)


2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher libvirtError: block copy still active: domain has active block job
2016-11-11 09:43:56.791 1455 ERROR oslo_messaging.rpc.dispatcher 

